name: healthcare
version: '1.0.0'
config-version: 2
profile: healthcare

model-paths:    ["models"]
macro-paths:    ["macros"]
test-paths:     ["tests"]
seed-paths:     ["seeds"]
analysis-paths: ["analyses"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - target
  - dbt_packages

models:
  healthcare:
    staging:
      +schema: staging
      +materialized: view
    marts:
      +schema: marts
      +materialized: table
